import { timingSafeEqual } from 'node:crypto';
import { consume,hash } from './storage';
export class ApiError extends Error { constructor(public status:number,message:string,public code='REQUEST_FAILED'){super(message);} }
export function originAllowed(request:Request){const origin=request.headers.get('origin');if(!origin)return true;const own=new URL(request.url).origin;const allowed=(process.env.EYWA_ALLOWED_ORIGINS||'https://eywwaa.github.io').split(',').map(s=>s.trim());return origin===own||allowed.includes(origin)||(process.env.NODE_ENV!=='production'&&/^http:\/\/(localhost|127\.0\.0\.1|terminal\.local)(:\d+)?$/.test(origin));}
export function headersFor(request:Request){const h=new Headers({'Cache-Control':'no-store','X-Content-Type-Options':'nosniff','Vary':'Origin'});const origin=request.headers.get('origin');if(origin&&originAllowed(request))h.set('Access-Control-Allow-Origin',origin);h.set('Access-Control-Allow-Methods','GET, POST, OPTIONS');h.set('Access-Control-Allow-Headers','Content-Type, Authorization');return h;}
export function json(request:Request,data:unknown,status=200){return Response.json(data,{status,headers:headersFor(request)});}
export async function boundary(request:Request,fn:()=>Promise<Response>){try{if(!originAllowed(request))throw new ApiError(403,'Cette origine n’est pas autorisée.','ORIGIN_DENIED');return await fn();}catch(e){if(e instanceof ApiError)return json(request,{code:e.code,message:e.message},e.status);if(e instanceof Error&&e.name==='ZodError')return json(request,{code:'INVALID_INPUT',message:'Vérifiez les informations saisies.'},400);console.error('[EYWA]',e instanceof Error?e.name:'Unexpected error');return json(request,{code:'TEMPORARY_ERROR',message:'Le service est momentanément indisponible. Réessayez dans un instant.'},503);}}
export async function readJson(request:Request,max=4096){if(!request.headers.get('content-type')?.includes('application/json'))throw new ApiError(415,'Format de requête invalide.');if(Number(request.headers.get('content-length')||0)>max)throw new ApiError(413,'La requête est trop volumineuse.');const reader=request.body?.getReader();if(!reader)throw new ApiError(400,'La requête est vide.');let size=0;const chunks:Uint8Array[]=[];while(true){const {done,value}=await reader.read();if(done)break;size+=value.length;if(size>max){await reader.cancel();throw new ApiError(413,'La requête est trop volumineuse.');}chunks.push(value);}try{return JSON.parse(Buffer.concat(chunks).toString());}catch{throw new ApiError(400,'La requête est invalide.');}}
export function rateLimit(request:Request,scope:string,max=12){const trusted=process.env.EYWA_TRUST_PROXY==='true';const identity=trusted?(request.headers.get('x-forwarded-for')?.split(',')[0].trim()||'unknown'):'global';if(!consume(`rate:${scope}:${hash(identity)}`,max,3600000))throw new ApiError(429,'Trop de demandes rapprochées. Réessayez un peu plus tard.','RATE_LIMIT');}
export function requireAdmin(request:Request){const expected=process.env.EYWA_ADMIN_TOKEN;const provided=request.headers.get('authorization')?.replace(/^Bearer /,'');if(!expected||!provided||provided.length!==expected.length||!timingSafeEqual(Buffer.from(provided),Buffer.from(expected)))throw new ApiError(401,'Accès réservé à l’administration EYWA.','UNAUTHORIZED');}
export function publicOrigin(request:Request){const configured=process.env.EYWA_PUBLIC_API_ORIGIN;if(configured)return new URL(configured).origin;if(process.env.NODE_ENV!=='production')return new URL(request.url).origin;throw new ApiError(503,'La préparation des images n’est pas encore activée.','ORIGIN_NOT_CONFIGURED');}
