import { lookup } from 'node:dns/promises';
import { request } from 'node:https';
import { isIP } from 'node:net';
import sharp from 'sharp';
export function isPublicAddress(ip:string){if(isIP(ip)===4){const [a,b]=ip.split('.').map(Number);return !(a===0||a===10||a===127||a>=224||a===169&&b===254||a===172&&b>=16&&b<=31||a===192&&b===168||a===100&&b>=64&&b<=127||a===198&&[18,19].includes(b)||a===192&&b===0||a===198&&b===51||a===203&&b===0);}return isIP(ip)===6&&/^[23][0-9a-f]{3}:/i.test(ip)&&!/^2001:(db8|0):/i.test(ip);}
export async function safeFetch(input:string,max=2*1024*1024,redirects=0):Promise<{bytes:Buffer;type:string;url:string}>{
 const url=new URL(input);if(url.protocol!=='https:'||url.username||url.password||(url.port&&url.port!=='443')||isIP(url.hostname)||url.hostname.endsWith('.local')||url.hostname==='localhost')throw new Error('Unsafe URL');
 const records=await lookup(url.hostname,{all:true});if(!records.length||records.some(r=>!isPublicAddress(r.address)))throw new Error('Private address');const pinned=records[0];
 const response=await new Promise<{bytes:Buffer;type:string;status:number;location?:string}>((resolve,reject)=>{const req=request(url,{method:'GET',family:pinned.family,headers:{'User-Agent':'EYWA-BrandPreview/1.0','Accept':'image/*,text/html;q=0.8'},lookup:((_h:unknown,options:{all?:boolean},cb:Function)=>options.all?cb(null,[pinned]):cb(null,pinned.address,pinned.family)) as never},res=>{const chunks:Buffer[]=[];let size=0;res.on('data',chunk=>{size+=chunk.length;if(size>max){req.destroy(new Error('Response too large'));return;}chunks.push(chunk);});res.on('end',()=>resolve({bytes:Buffer.concat(chunks),type:String(res.headers['content-type']||''),status:res.statusCode||500,location:res.headers.location}));res.on('error',reject);});req.setTimeout(12000,()=>req.destroy(new Error('Fetch timeout')));req.on('error',reject);req.end();});
 if(response.status>=300&&response.status<400&&response.location){if(redirects>=3)throw new Error('Too many redirects');return safeFetch(new URL(response.location,url).href,max,redirects+1);}if(response.status!==200)throw new Error('Resource unavailable');return{bytes:response.bytes,type:response.type,url:url.href};
}
export async function fetchLogo(url:string){const res=await safeFetch(url);if(!/^image\/(png|jpeg|webp|svg\+xml)/i.test(res.type))throw new Error('Not an image');if(res.type.includes('svg')&&/<!ENTITY|<!DOCTYPE|<script|<foreignObject|(?:href|src)\s*=\s*["'](?:https?:|\/\/|data:)|url\(/i.test(res.bytes.toString()))throw new Error('Unsafe SVG');return sharp(res.bytes,{limitInputPixels:16000000}).resize(1024,512,{fit:'inside',withoutEnlargement:true}).trim().png().toBuffer();}
