import type { Branding } from './types';
type Preset = { name: string; domain: string; colors: [string, string, string]; side?: string; logo?: string; style: string; location: string; atmosphere: string; rationale: string; accent: 'line' | 'edge' | 'diagonal' | 'none'; lighting: 'warm' | 'neutral' };
const definitions: Record<string, Preset> = {
  celio: { name: 'celio', domain: 'celio.com', colors: ['#161616','#FFFFFF','#D82333'], style: 'Retail masculin contemporain, noir franc, rouge ponctuel, composition directe et accueillante.', location: 'Magasin de vêtements celio', atmosphere: 'Portants de vêtements, lumière chaude, circulation dégagée et accueil convivial.', rationale: 'Une façade noire, un nom blanc et un filet rouge. Le noyer apporte une chaleur discrète à une activation en boutique.', accent: 'line', lighting: 'warm' },
  nike: { name: 'Nike', domain: 'nike.com', colors: ['#F3F2EE','#161616','#E85930'], side: '#171717', logo: '/brands/nike.svg', style: 'Culture sportive urbaine, contraste graphique, matériaux bruts et composition énergique.', location: 'Activation sportive Nike', atmosphere: 'Boutique sportive contemporaine, béton clair, lignes graphiques et lumière directionnelle.', rationale: 'Un contraste clair et noir, un signe ample et une touche graphique vive. Une présence qui s’accorde à une activation sportive.', accent: 'diagonal', lighting: 'neutral' },
  dior: { name: 'Dior', domain: 'dior.com', colors: ['#E9E7E2','#373630','#B7A184'], logo: '/brands/dior.svg', style: 'Couture, gris perle, symétrie, discrétion des contrastes et élégance architecturale.', location: 'Réception dans une boutique Dior', atmosphere: 'Pierre claire, mobilier délicat, fleurs blanches et lumière douce de réception.', rationale: 'Gris perle, signature sombre et détails subtils. Le plateau noyer reste présent, dans une composition calme et épurée.', accent: 'edge', lighting: 'warm' },
  cupra: { name: 'CUPRA', domain: 'cupraofficial.com', colors: ['#24292A','#B9977A','#B9977A'], side: '#303B3D', style: 'Design automobile contemporain, anthracite minéral, cuivre et lignes tendues.', location: 'CUPRA City Garage', atmosphere: 'Showroom automobile, béton, accents cuivrés, lumière théâtrale et ambiance urbaine.', rationale: 'Anthracite profond et accents cuivre. La finition satinée dialogue avec l’univers automobile et le noyer du comptoir.', accent: 'edge', lighting: 'warm' },
  renault: { name: 'Renault', domain: 'renault.com', colors: ['#EAE9E4','#171717','#F4D544'], side: '#252525', logo: '/brands/renault.svg', style: 'Design automobile lisible, noir et blanc, géométrie simple et accent jaune mesuré.', location: 'Showroom Renault', atmosphere: 'Concession lumineuse, grandes baies vitrées, architecture ouverte, voiture en arrière-plan.', rationale: 'Un fond clair, le losange en noir et une ligne jaune. Une composition lumineuse pour accueillir les visiteurs en showroom.', accent: 'line', lighting: 'neutral' },
};
export const PRESETS: Record<string, Branding> = Object.fromEntries(Object.entries(definitions).map(([key, p]) => [key, {
  brand: { name:p.name, domain:p.domain, positioning:p.style, visual_style:p.style, primary_colors:[p.colors[0],p.colors[1]], secondary_colors:[p.colors[2]], keywords:[p.location, p.lighting === 'warm' ? 'Chaleur' : 'Contraste', 'Noyer'], environment:p.atmosphere },
  bar: { front_color:p.colors[0], side_color:p.side || p.colors[0], logo:p.logo || '', logo_color:p.colors[1], accent_color:p.colors[2], accent_elements:[p.accent], lighting:p.lighting, finish:key==='cupra'?'satin':'matte' },
  scene: { location_type:p.location, lighting:p.lighting==='warm'?'Lumière chaude et douce':'Lumière naturelle et contrastée', atmosphere:p.atmosphere, image_prompt:'' }, rationale:p.rationale,
  sources:[],
}]));
// These are explicitly labelled EYWA example directions, not automatic research
// or official brand guidelines. Unverified marks use a plain brand name.
export const exampleNames = ['Celio','Nike','Dior','Cupra','Renault'];
