'use client';
import { useCallback, useEffect, useRef, useState } from 'react';
import dynamic from 'next/dynamic';
import { ArrowUpRight, ArrowLeft, ArrowRight, Check, Image as ImageIcon, RotateCcw } from 'lucide-react';
import { PRESETS, exampleNames } from '@/lib/presets';
import { asset, normalizeBrand, type Analysis, type Branding, type Visuals, type Candidate } from '@/lib/types';
const BarViewer=dynamic(()=>import('./BarViewer'),{ssr:false,loading:()=> <div className="viewer viewer-placeholder"><span className="fine-spinner"/></div>});
const neutral:Branding={...PRESETS.dior,brand:{...PRESETS.dior.brand,name:'EYWA',domain:'',keywords:[]},bar:{...PRESETS.dior.bar,front_color:'#e6e2d8',side_color:'#e6e2d8',logo:'',logo_color:'#1b3c2e',accent_elements:['none']}};
const QUOTE='https://eywwaa.github.io/eywa-site/devis-instantane.html';
type Ready=Extract<Analysis,{status:'ready'}>;
export default function Configurator(){
 const [name,setName]=useState(''),[result,setResult]=useState<Ready|null>(null),[phase,setPhase]=useState<'idle'|'research'|'images'>('idle'),[error,setError]=useState(''),[choices,setChoices]=useState<Candidate[]>([]),[needsDomain,setNeedsDomain]=useState(false),[domain,setDomain]=useState(''),[visuals,setVisuals]=useState<Visuals>({}),[apiBase,setApiBase]=useState(''),[live,setLive]=useState(false),[embedded,setEmbedded]=useState(false),[ready,setReady]=useState(false);
 const abort=useRef<AbortController|null>(null),sequence=useRef(0),resultsRef=useRef<HTMLDivElement>(null),inputRef=useRef<HTMLInputElement>(null);
 useEffect(()=>{const embed=new URLSearchParams(location.search).get('embed')==='1';setEmbedded(embed);let disposed=false;const boot=async()=>{let base='';let available=false;try{const r=await fetch(asset('/runtime-config.json'),{cache:'no-store'});const cfg=await r.json();base=typeof cfg.apiBase==='string'?cfg.apiBase.replace(/\/$/,''):'';if(base&&!/^https:\/\//.test(base))base='';if(process.env.NEXT_PUBLIC_STATIC_EXPORT!=='1'||base){const s=await fetch(`${base}/api/status`,{signal:AbortSignal.timeout(8000)});const info=await s.json();available=info.liveEnabled===true;}}catch{}if(!disposed){setApiBase(base);setLive(available);setReady(true);}};void boot();
  const resize=new ResizeObserver(()=>{if(embed)window.parent.postMessage({type:'eywa:height',height:Math.ceil(document.documentElement.scrollHeight)},location.origin);});resize.observe(document.body);return()=>{disposed=true;resize.disconnect();abort.current?.abort();};},[]);
 const example=(label:string)=>{const key=normalizeBrand(label),b=PRESETS[key];if(!b)return;sequence.current++;abort.current?.abort();setPhase('idle');setName(label);setError('');setNeedsDomain(false);setChoices([]);setVisuals({});setResult({status:'ready',id:`example-${key}`,branding:b,cached:true,mode:'example',logoStatus:b.bar.logo?'verified':'wordmark',modelUrl:asset('/models/eywa-bar-v1.glb'),modelApproved:false,imagesReady:false});};
 const generateImages=useCallback(async(r:Ready,current:number,signal:AbortSignal)=>{setPhase('images');try{const response=await fetch(`${apiBase}/api/images`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({configurationId:r.id}),signal});const data=await response.json();if(!response.ok)throw new Error(data.message||'La mise en situation n’a pas pu être préparée.');if(current===sequence.current)setVisuals(data);}catch(e){if(current===sequence.current&&!signal.aborted)setVisuals({errors:{scene:e instanceof Error?e.message:'La préparation des images a été interrompue.'}});}finally{if(current===sequence.current)setPhase('idle');}},[apiBase]);
 async function submit(selectedDomain?:string){const value=name.trim();if(value.length<2){setError('Indiquez le nom de votre marque.');inputRef.current?.focus();return;}if(!live){if(PRESETS[normalizeBrand(value)]){example(value);return;}setError('La création pour votre marque sera disponible prochainement. Vous pouvez déjà explorer les cinq exemples ci-dessous.');return;}
  const current=++sequence.current;abort.current?.abort();const controller=new AbortController();abort.current=controller;setPhase('research');setError('');setChoices([]);setNeedsDomain(false);setVisuals({});const timeout=setTimeout(()=>controller.abort('timeout'),240000);
  try{const response=await fetch(`${apiBase}/api/analyze`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:value,domain:selectedDomain||domain||undefined}),signal:controller.signal});const data:Analysis&{message?:string}=await response.json();if(current!==sequence.current)return;if(!response.ok)throw new Error(data.message||'Nous n’avons pas pu préparer votre proposition.');if(data.status==='ambiguous'){setChoices(data.candidates);setPhase('idle');return;}if(data.status==='not_found'){setError(data.message);setNeedsDomain(true);setPhase('idle');return;}setResult(data);clearTimeout(timeout);if(data.imagesReady)await generateImages(data,current,controller.signal);else setPhase('idle');
  }catch(e){if(current===sequence.current){setPhase('idle');setError(controller.signal.aborted?'La recherche prend plus de temps que prévu. Votre saisie a été conservée ; réessayez dans un instant.':e instanceof Error?e.message:'La connexion a été interrompue. Réessayez.');}}finally{clearTimeout(timeout);}}
 const brand=result?.branding||neutral;
 const quote=new URL(QUOTE);if(result){quote.searchParams.set('marque',brand.brand.name);quote.searchParams.set('configuration',result.id);quote.searchParams.set('personnalisation','bar,gobelets,latte');}
 return <div className={`studio ${embedded?'embedded':''}`}>
  {!embedded&&<header className="studio-header"><a href="https://eywwaa.github.io/eywa-site/" className="wordmark" aria-label="EYWA, retour au site">EYWA<span>COFFEE CATERING</span></a><a href="https://eywwaa.github.io/eywa-site/" className="back-link"><ArrowLeft size={15}/> Retour au site</a><a href={quote.href} className="header-contact">Parlons de votre événement <ArrowUpRight size={16}/></a></header>}
  <main>
   <section className="studio-intro"><p className="overline"><span/> L’ATELIER DE PERSONNALISATION</p><h1>Visualisez votre coffee bar<br/>aux couleurs de <em>votre marque.</em></h1><p className="intro-copy">Votre univers. Notre savoir-faire. Une rencontre sur mesure.</p></section>
   <section className="workspace" aria-label="Personnaliser votre coffee bar">
    <div className="brief-panel"><span className="step-label">01 — VOTRE IDENTITÉ</span><h2>Tout commence<br/>par votre nom.</h2><p>Nous imaginons un coffee bar qui trouve naturellement sa place chez vous.</p>
     <form onSubmit={e=>{e.preventDefault();void submit();}}><label htmlFor="brand-name">Nom de votre marque</label><div className="brand-input"><input ref={inputRef} id="brand-name" placeholder="Ex. Celio" value={name} maxLength={100} onChange={e=>{setName(e.target.value);setError('');setNeedsDomain(false);setDomain('');}} autoComplete="organization" required minLength={2} aria-describedby={error?'brand-error':undefined}/>{name&&<button type="button" aria-label="Effacer le nom" onClick={()=>{setName('');setDomain('');setError('');setChoices([]);inputRef.current?.focus();}}>×</button>}</div>
      {needsDomain&&<div className="domain-field"><label htmlFor="brand-domain">Adresse du site de votre marque</label><input id="brand-domain" value={domain} onChange={e=>setDomain(e.target.value)} placeholder="exemple.fr" inputMode="url"/></div>}
      <button className="create-button" type="submit" disabled={phase!=='idle'||!ready}>{phase!=='idle'?<><span className="fine-spinner"/> {phase==='research'?'Votre univers prend forme…':'Préparation des images…'}</>:<>Créer mon bar <ArrowRight size={18}/></>}</button>
     </form>
     {error&&<p className="inline-error" id="brand-error" role="alert">{error}</p>}
     {choices.length>0&&<div className="company-choices"><p>Nous avons trouvé plusieurs entreprises portant ce nom. Laquelle souhaitez-vous ?</p>{choices.map(c=><button key={c.domain} onClick={()=>void submit(c.domain)}><strong>{c.name}</strong><span>{c.description}</span><small>{c.domain}</small></button>)}</div>}
     <div className="example-brands"><span>EXPLORER UNE INSPIRATION</span><div>{exampleNames.map(label=><button type="button" key={label} aria-pressed={result?.mode==='example'&&normalizeBrand(brand.brand.name)===normalizeBrand(label)} onClick={()=>example(label)}>{label}</button>)}</div></div>
     <div className="brief-foot"><span className="tiny-rule"/><p>Le bar, les gobelets,<br/>jusque dans la tasse.</p></div>
    </div>
    <div className="visual-panel" ref={resultsRef}>
      <BarViewer branding={brand} modelUrl={result?.modelUrl}/>
      <div className="design-caption"><div><span className="step-label">{result?'VOTRE DIRECTION ARTISTIQUE':'LE POINT DE DÉPART'}</span><h2>{result?<>EYWA <span className="collab-times">×</span> {brand.brand.name}</>:'Un bar. Toutes vos idées.'}</h2></div><div className="palette" aria-label="Palette de la proposition">{[brand.bar.front_color,brand.bar.logo_color,brand.bar.accent_color,'#493020'].map((color,i)=><span key={i} style={{background:color}} title={i===3?'Noyer foncé':color}/>)}</div></div>
      <p className="design-description">{result?brand.rationale:'Une façade lisse, un plan de travail en noyer et toute l’attention d’un véritable coffee shop.'}</p>
      {result&&<div className="proposal-meta"><span><Check size={13}/> {brand.bar.finish==='matte'?'Finition mate':'Finition satinée'}</span><span><Check size={13}/> Plan de travail noyer</span><span><Check size={13}/> {brand.bar.lighting==='warm'?'Lumière chaude':'Lumière neutre'}</span></div>}
      <p className="preview-note">{result?.mode==='example'?'Exemple de direction artistique EYWA. ':''}{!result?.modelApproved?'Modèle de présentation — proportions définitives à valider. ':''}{result?.logoStatus==='wordmark'?'Nom de marque affiché ; logo officiel à confirmer.':''}</p>
    </div>
   </section>
   {phase==='research'&&<div className="progress-message" role="status" aria-live="polite"><span className="scan-line"/><p>Nous analysons votre univers de marque…</p><span>Identité visuelle, matières et ambiance de vos espaces.</span><button onClick={()=>{sequence.current++;abort.current?.abort();setPhase('idle');}}>Annuler</button></div>}
   {result&&<section className="proposal" aria-label="Votre proposition personnalisée"><div className="proposal-heading"><div><p className="overline">02 — IMAGINEZ LE JOUR J</p><h2>Déjà chez <em>vous.</em></h2></div><p>{brand.scene.location_type}<br/><span>{brand.scene.lighting}</span></p></div>
     <div className="photo-layout"><figure className="scene-photo">{visuals.scene?<img src={visuals.scene} alt={`Projection du coffee bar EYWA dans un environnement ${brand.brand.name}`} loading="lazy"/>:<div className="photo-unavailable"><ImageIcon size={26} strokeWidth={1}/><span>{phase==='images'?'Votre mise en situation prend forme…':'Votre bar, dans votre univers'}</span><p>{phase==='images'?'Le bar et son habillage sont conservés.':result.mode==='example'?'La photo sera disponible après l’intégration du vrai bar EYWA.':'La préparation de cette photo nécessite les références EYWA.'}</p>{visuals.errors?.scene&&<p role="alert">{visuals.errors.scene}</p>}</div>}<figcaption><span>01</span> LA MISE EN SITUATION</figcaption></figure>
     <div className="detail-photos">{(['cup','latte'] as const).map((key,i)=><figure key={key}>{visuals[key]?<img src={visuals[key]} alt={key==='cup'?`Gobelet personnalisé ${brand.brand.name}`:`Logo ${brand.brand.name} intégré à la mousse du latte`} loading="lazy"/>:<div className="detail-unavailable"><span>{key==='cup'?'Votre signature.':'Jusqu’à la dernière tasse.'}</span><p>{phase==='images'?'Préparation en cours…':'Photo maître à intégrer'}</p>{visuals.errors?.[key]&&<small role="alert">{visuals.errors[key]}</small>}</div>}<figcaption><span>0{i+2}</span>{key==='cup'?' LE GOBELET PERSONNALISÉ':' LE LOGO SUR LA MOUSSE'}</figcaption></figure>)}</div></div>
     {Object.keys(visuals.errors||{}).length>0&&result.mode==='live'&&result.imagesReady&&<button className="retry-images" onClick={()=>{abort.current?.abort();const c=new AbortController();abort.current=c;void generateImages(result,sequence.current,c.signal);}} disabled={phase!=='idle'}><RotateCcw size={15}/> Réessayer les images manquantes</button>}
     {result.mode==='live'&&brand.sources.length>0&&<details className="sources"><summary>Références de cette direction artistique</summary>{brand.sources.map(s=><a key={s.url} href={s.url} target="_blank" rel="noreferrer">{s.title} <ArrowUpRight size={12}/></a>)}</details>}
     <div className="reservation"><div><p>Cette idée pourrait être la vôtre.</p><h2>Donnons-lui <em>rendez-vous.</em></h2></div><a className="reservation-button" href={quote.href} target={embedded?'_top':undefined}>Imaginer mon événement <ArrowUpRight size={20}/></a></div>
     <p className="legal-note">Projection de personnalisation, sans partenariat avec la marque représentée. L’habillage final est validé avec vous avant production.</p>
   </section>}
  </main>
  {!embedded&&<footer className="studio-footer"><span>EYWA — COFFEE CATERING</span><span>Charleville-Mézières · Reims · Et au-delà</span><a href="mailto:contact.eywa08@gmail.com">Un projet particulier ? Écrivez-nous <ArrowUpRight size={13}/></a></footer>}
 </div>
}
