import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync,mkdtempSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { homography,project,colorSurface,printFoam } from '../server/compositor';
import { isPublicAddress } from '../server/safe-fetch';
import { BrandingSchema } from '../lib/types';
import { PRESETS } from '../lib/presets';
import { MasterSchema } from '../server/masters';

test('All five art directions conform to the contract and keep distinct surface designs',()=>{for(const p of Object.values(PRESETS))BrandingSchema.parse(p);assert.equal(new Set(Object.values(PRESETS).map(p=>p.bar.front_color)).size,5);assert.equal(Object.values(PRESETS).some(p=>'geometry' in p.bar),false);});
test('Calibration maps all four corners without moving protected content',()=>{const from:[[number,number],[number,number],[number,number],[number,number]]=[[.1,.2],[.8,.1],[.9,.8],[.2,.9]];const to:[[number,number],[number,number],[number,number],[number,number]]=[[0,0],[1,0],[1,1],[0,1]];const h=homography(from,to);for(let i=0;i<4;i++){const p=project(h,...from[i]);assert.ok(Math.abs(p[0]-to[i][0])<1e-8);assert.ok(Math.abs(p[1]-to[i][1])<1e-8);}});
test('Cup/bar recoloring preserves every pixel outside the approved surface',()=>{const data=new Uint8Array(100*100*4).fill(220),before=data.slice();colorSurface({data,width:100,height:100},[[.3,.3],[.7,.3],[.7,.7],[.3,.7]],PRESETS.celio,null);let changed=0;for(let y=0;y<100;y++)for(let x=0;x<100;x++){const i=(y*100+x)*4;if(x<30||x>70||y<30||y>70)assert.deepEqual(data.slice(i,i+4),before.slice(i,i+4));if(data[i]!==before[i])changed++;assert.equal(data[i+3],before[i+3]);}assert.ok(changed>1000);});
test('Latte imprint changes only logo pixels within foam and preserves foam texture',()=>{const data=new Uint8Array(100*100*4).fill(220),before=data.slice();const logo={data:new Uint8Array(16*8*4).fill(255),width:16,height:8};printFoam({data,width:100,height:100},{cx:.5,cy:.5,rx:.28,ry:.24,rotation:0},logo);for(let y=0;y<100;y++)for(let x=0;x<100;x++){const i=(y*100+x)*4;if(x<30||x>70||y<30||y>70)assert.deepEqual(data.slice(i,i+4),before.slice(i,i+4));assert.equal(data[i+3],before[i+3]);}assert.ok(data[(50*100+50)*4]<220);assert.notEqual(data[(50*100+50)*4],data[(50*100+51)*4]);});
test('Remote image fetch excludes internal, metadata, multicast and reserved addresses',()=>{for(const ip of ['127.0.0.1','10.0.0.1','169.254.169.254','172.16.0.1','192.168.1.1','100.64.0.1','::1','fc00::1','fe80::1','::ffff:127.0.0.1','2001:db8::1'])assert.equal(isPublicAddress(ip),false,ip);assert.equal(isPublicAddress('8.8.8.8'),true);});
test('One small GLB contains fixed body, flat faces, walnut, espresso machine, grinder and wheels',()=>{const b=readFileSync('public/models/eywa-bar-v1.glb');assert.equal(b.readUInt32LE(0),0x46546c67);assert.ok(b.length<250000);const gltf=JSON.parse(b.subarray(20,20+b.readUInt32LE(12)).toString());const names=gltf.nodes.map((n:{name:string})=>n.name);for(const name of ['BAR_FRONT','BAR_LEFT','BAR_RIGHT','COUNTERTOP','ESPRESSO_MACHINE','GRINDER_BODY','WHEELS'])assert.ok(names.some((n:string)=>n===name||n.startsWith(name+'_')),name);});
test('The detailed v3 GLB keeps the protected furniture and adds equipment details within its size budget',()=>{const b=readFileSync('public/models/eywa-bar-v3.glb');assert.equal(b.readUInt32LE(0),0x46546c67);assert.ok(b.length<2000000);const gltf=JSON.parse(b.subarray(20,20+b.readUInt32LE(12)).toString());const names=gltf.nodes.map((n:{name:string})=>n.name);for(const name of ['BAR_FRONT','BAR_LEFT','BAR_RIGHT','COUNTERTOP','ESPRESSO_MACHINE','GRINDER_BODY','WHEELS'])assert.ok(names.some((n:string)=>n===name||n.startsWith(name+'_')),name);const root=gltf.nodes.find((n:{name:string})=>n.name==='EYWA_PHOTO_BASED_FIXED_BAR') as {extras?:Record<string,unknown>}|undefined;assert.equal(root?.extras?.immutable,true);assert.equal(root?.extras?.version,'3.0');for(const name of ['INDIVIDUAL_BEANS','MACHINE_SCREW','CUP_BRAND','CASTER_BRAKE'])assert.ok(names.some((n:string)=>n===name||n.startsWith(name+'_')),name);});
test('Master calibration rejects a degenerate printable surface',()=>{const file='a'.repeat(64);const valid={version:'test',approved:false,model:`${file}.glb`,bar:{image:`${file}.png`,cutout:`${file}.png`,front:[[.1,.1],[.9,.1],[.9,.9],[.1,.9]],side:null,placement:{x:.1,y:.1,width:.5}},cup:{image:`${file}.png`,surface:[[.1,.1],[.9,.1],[.9,.9],[.1,.9]]},latte:{image:`${file}.png`,foam:{cx:.5,cy:.5,rx:.2,ry:.2,rotation:0}}};assert.doesNotThrow(()=>MasterSchema.parse(valid));assert.throws(()=>MasterSchema.parse({...valid,bar:{...valid.bar,front:[[.2,.2],[.4,.4],[.6,.6],[.8,.8]]}}));});
